eval $(./dependencies.sh)
generator="Ninja Multi-Config"

rmCmakeTrash() {
  echo -e "clearing the \"build/\" directory"
  rm -rf ${paths["build"]}/* ${paths["build"]}/.*
  echo -e "the \"build/\" directory has been cleared\n"
}

if [ $# -eq 1 ]; then
  if [ $1 == "--jci" ]; then
    echo -e "\nactivated cleaning mode (--jci) . we just delete the files and directories generated by cmake\n"
    rmCmakeTrash
    exit 0
  elif [ $1 == "--replace" ] || [ $1 == "-r" ]; then
    echo -e "\ndeleting past generation files is activated (--replace)\n"
    rmCmakeTrash
  elif [ $1 == "--help" ]; then
    echo "don't use arguments to start the normal generation"
    echo -e "\t--help -> to show this message"
    echo -e "\t--replace / -r -> to remove files of the previous generation"
    echo -e "\t--jci -> deletes files and directories generated by cmake"
    exit 0
  else
    echo -e -n "\nunknown argument \""
    echo -e $1"\"\n"
    ./generate.sh --help
    exit 0
  fi
fi
cmake -S ${paths["cmake"]} -B ${paths["build"]} -G "${generator}"
